export const SystemRoleCode = {
  SuperAdministrator: 'SUPER_ADMIN',
  Trainer: 'TRAINER',
  Trainee: 'TRAINEE',
} as const;

export type SystemRoleCode = (typeof SystemRoleCode)[keyof typeof SystemRoleCode];

export const PermissionCode = {
  RolesRead: 'roles.read',
  RolesCreate: 'roles.create',
  RolesUpdate: 'roles.update',
  RolesDelete: 'roles.delete',
  PermissionsRead: 'permissions.read',
  UsersRead: 'users.read',
  UserRolesRead: 'users.roles.read',
  UserRolesAssign: 'users.roles.assign',
  UserRolesRemove: 'users.roles.remove',
  SystemAuthEventsRead: 'system.auth-events.read',
  BrandsRead: 'brands.read',
  BrandsCreate: 'brands.create',
  BrandsUpdate: 'brands.update',
  BrandsArchive: 'brands.archive',
  BrandsReactivate: 'brands.reactivate',
  BrandAccessRead: 'brand_access.read',
  BrandAccessAssign: 'brand_access.assign',
  BrandAccessRemove: 'brand_access.remove',
  ParticipantsRead: 'participants.read',
  ParticipantsCreate: 'participants.create',
  ParticipantsUpdate: 'participants.update',
  ParticipantsDisable: 'participants.disable',
  ParticipantsReactivate: 'participants.reactivate',
  ParticipantsInvite: 'participants.invite',
  TrainersRead: 'trainers.read',
  TrainersCreate: 'trainers.create',
  TrainersUpdate: 'trainers.update',
  TrainersDisable: 'trainers.disable',
  TrainersReactivate: 'trainers.reactivate',
  TrainersInvite: 'trainers.invite',
  StaffNikReadFull: 'staff.nik.read_full',
  EnrollmentsRead: 'enrollments.read',
  EnrollmentsCreate: 'enrollments.create',
  EnrollmentsUpdate: 'enrollments.update',
  EnrollmentsCancel: 'enrollments.cancel',
  EnrollmentsReadSelf: 'enrollments.read_self',
  CurriculaRead: 'curricula.read',
  CurriculaCreate: 'curricula.create',
  CurriculaUpdate: 'curricula.update',
  CurriculaArchive: 'curricula.archive',
  CurriculumVersionsRead: 'curriculum_versions.read',
  CurriculumVersionsCreate: 'curriculum_versions.create',
  CurriculumVersionsUpdate: 'curriculum_versions.update',
  CurriculumVersionsPublish: 'curriculum_versions.publish',
  CurriculumWeeksManage: 'curriculum_weeks.manage',
  CurriculumModulesManage: 'curriculum_modules.manage',
  MaterialsRead: 'materials.read',
  MaterialsCreate: 'materials.create',
  MaterialsUpdate: 'materials.update',
  MaterialsRemove: 'materials.remove',
  MaterialsReorder: 'materials.reorder',
  MaterialsUpload: 'materials.upload',
  LearningContentReadSelf: 'learning_content.read_self',
  LearningProgressRead: 'learning_progress.read',
  TrainingProgressReadSelf: 'training_progress.read_self',
  ExamsRead: 'exams.read',
  ExamsCreate: 'exams.create',
  ExamsUpdate: 'exams.update',
  QuestionsRead: 'questions.read',
  QuestionsCreate: 'questions.create',
  QuestionsUpdate: 'questions.update',
  QuestionsApprove: 'questions.approve',
  QuestionsAiGenerate: 'questions.ai_generate',
  ExamAttemptsStartSelf: 'exam_attempts.start_self',
  ExamAttemptsAnswerSelf: 'exam_attempts.answer_self',
  ExamAttemptsSubmitSelf: 'exam_attempts.submit_self',
  ExamAttemptsReadSelf: 'exam_attempts.read_self',
  ExamResultsRead: 'exam_results.read',
  ReportsRead: 'reports.read',
  ReportsExport: 'reports.export',
  CertificatesRead: 'certificates.read',
  CertificatesIssue: 'certificates.issue',
  CertificatesRevoke: 'certificates.revoke',
  CertificatesReadSelf: 'certificates.read_self',
} as const;

export type PermissionCode = (typeof PermissionCode)[keyof typeof PermissionCode];

export const systemRoles = [
  {
    code: SystemRoleCode.SuperAdministrator,
    name: 'Super Administrator',
    description: 'Centralized privileged authorization bypass for system administration.',
  },
  {
    code: SystemRoleCode.Trainer,
    name: 'Trainer',
    description:
      'Authenticated trainer baseline; business permissions are assigned by future modules.',
  },
  {
    code: SystemRoleCode.Trainee,
    name: 'Trainee',
    description:
      'Authenticated trainee baseline; business permissions are assigned by future modules.',
  },
] as const;

export const systemPermissions = [
  {
    code: PermissionCode.RolesRead,
    name: 'Read roles',
    description: 'View role definitions and their assigned permissions.',
    resource: 'roles',
    action: 'read',
  },
  {
    code: PermissionCode.RolesCreate,
    name: 'Create roles',
    description: 'Create custom authorization roles.',
    resource: 'roles',
    action: 'create',
  },
  {
    code: PermissionCode.RolesUpdate,
    name: 'Update roles',
    description: 'Update custom roles and their permission assignments.',
    resource: 'roles',
    action: 'update',
  },
  {
    code: PermissionCode.RolesDelete,
    name: 'Deactivate roles',
    description: 'Deactivate custom authorization roles.',
    resource: 'roles',
    action: 'delete',
  },
  {
    code: PermissionCode.PermissionsRead,
    name: 'Read permissions',
    description: 'View application-defined permission capabilities.',
    resource: 'permissions',
    action: 'read',
  },
  {
    code: PermissionCode.UsersRead,
    name: 'Read users',
    description: 'Read authorization-target user records.',
    resource: 'users',
    action: 'read',
  },
  {
    code: PermissionCode.UserRolesRead,
    name: 'Read user roles',
    description: 'View role assignments for a user.',
    resource: 'users.roles',
    action: 'read',
  },
  {
    code: PermissionCode.UserRolesAssign,
    name: 'Assign user roles',
    description: 'Assign active roles to users.',
    resource: 'users.roles',
    action: 'assign',
  },
  {
    code: PermissionCode.UserRolesRemove,
    name: 'Remove user roles',
    description: 'Remove a role assignment while preserving the last-super-admin invariant.',
    resource: 'users.roles',
    action: 'remove',
  },
  {
    code: PermissionCode.SystemAuthEventsRead,
    name: 'Read authorization audit events',
    description: 'Read authorization-related system audit events.',
    resource: 'system.auth-events',
    action: 'read',
  },
  {
    code: PermissionCode.BrandsRead,
    name: 'Read brands',
    description: "Read Brands within the caller's authorized Brand scope.",
    resource: 'brands',
    action: 'read',
  },
  {
    code: PermissionCode.BrandsCreate,
    name: 'Create brands',
    description: 'Create Brand domain records.',
    resource: 'brands',
    action: 'create',
  },
  {
    code: PermissionCode.BrandsUpdate,
    name: 'Update brands',
    description: 'Update Brand display metadata.',
    resource: 'brands',
    action: 'update',
  },
  {
    code: PermissionCode.BrandsArchive,
    name: 'Archive brands',
    description: 'Archive active Brand domain records.',
    resource: 'brands',
    action: 'archive',
  },
  {
    code: PermissionCode.BrandsReactivate,
    name: 'Reactivate brands',
    description: 'Reactivate archived Brand domain records.',
    resource: 'brands',
    action: 'reactivate',
  },
  {
    code: PermissionCode.BrandAccessRead,
    name: 'Read Brand access',
    description: 'View Trainer Brand scope assignments.',
    resource: 'brand_access',
    action: 'read',
  },
  {
    code: PermissionCode.BrandAccessAssign,
    name: 'Assign Brand access',
    description: 'Assign active Brand scope to Trainers.',
    resource: 'brand_access',
    action: 'assign',
  },
  {
    code: PermissionCode.BrandAccessRemove,
    name: 'Remove Brand access',
    description: 'Remove Trainer Brand scope assignments.',
    resource: 'brand_access',
    action: 'remove',
  },
  {
    code: PermissionCode.ParticipantsRead,
    name: 'Read participants',
    description: 'Read participants within the authorized pre-enrollment management scope.',
    resource: 'participants',
    action: 'read',
  },
  {
    code: PermissionCode.ParticipantsCreate,
    name: 'Create participants',
    description: 'Provision Participant identities and first-activation invitations.',
    resource: 'participants',
    action: 'create',
  },
  {
    code: PermissionCode.ParticipantsUpdate,
    name: 'Update participants',
    description: 'Update safe Participant profile fields within the management scope.',
    resource: 'participants',
    action: 'update',
  },
  {
    code: PermissionCode.ParticipantsDisable,
    name: 'Disable participants',
    description: 'Disable Participant accounts within the management scope.',
    resource: 'participants',
    action: 'disable',
  },
  {
    code: PermissionCode.ParticipantsReactivate,
    name: 'Reactivate participants',
    description: 'Reactivate Participant accounts within the management scope.',
    resource: 'participants',
    action: 'reactivate',
  },
  {
    code: PermissionCode.ParticipantsInvite,
    name: 'Invite participants',
    description: 'Issue first-activation invitations for invited Participants.',
    resource: 'participants',
    action: 'invite',
  },
  {
    code: PermissionCode.TrainersRead,
    name: 'Read trainers',
    description: 'Read Trainer identity profiles.',
    resource: 'trainers',
    action: 'read',
  },
  {
    code: PermissionCode.TrainersCreate,
    name: 'Create trainers',
    description: 'Provision Trainer identities and first-activation invitations.',
    resource: 'trainers',
    action: 'create',
  },
  {
    code: PermissionCode.TrainersUpdate,
    name: 'Update trainers',
    description: 'Update safe Trainer profile fields.',
    resource: 'trainers',
    action: 'update',
  },
  {
    code: PermissionCode.TrainersDisable,
    name: 'Disable trainers',
    description: 'Disable Trainer accounts.',
    resource: 'trainers',
    action: 'disable',
  },
  {
    code: PermissionCode.TrainersReactivate,
    name: 'Reactivate trainers',
    description: 'Reactivate Trainer accounts.',
    resource: 'trainers',
    action: 'reactivate',
  },
  {
    code: PermissionCode.TrainersInvite,
    name: 'Invite trainers',
    description: 'Issue first-activation invitations for invited Trainers.',
    resource: 'trainers',
    action: 'invite',
  },
  {
    code: PermissionCode.StaffNikReadFull,
    name: 'Read full staff NIK',
    description: 'Read a full decrypted staff NIK through an explicitly audited operation.',
    resource: 'staff.nik',
    action: 'read_full',
  },
  {
    code: PermissionCode.EnrollmentsRead,
    name: 'Read training enrollments',
    description: 'Read training enrollments within the authorized Brand scope.',
    resource: 'enrollments',
    action: 'read',
  },
  {
    code: PermissionCode.EnrollmentsCreate,
    name: 'Create training enrollments',
    description: 'Assign one or more Brand training enrollments to a Participant.',
    resource: 'enrollments',
    action: 'create',
  },
  {
    code: PermissionCode.EnrollmentsUpdate,
    name: 'Update training enrollments',
    description: 'Update planned Weeks for a not-started training enrollment.',
    resource: 'enrollments',
    action: 'update',
  },
  {
    code: PermissionCode.EnrollmentsCancel,
    name: 'Cancel training enrollments',
    description: 'Cancel a not-started training enrollment while retaining history.',
    resource: 'enrollments',
    action: 'cancel',
  },
  {
    code: PermissionCode.EnrollmentsReadSelf,
    name: 'Read own training enrollments',
    description: 'Read only the authenticated Participant training assignments.',
    resource: 'enrollments',
    action: 'read_self',
  },
  {
    code: PermissionCode.CurriculaRead,
    name: 'Read curricula',
    description: 'Read curricula within the authorized Brand scope.',
    resource: 'curricula',
    action: 'read',
  },
  {
    code: PermissionCode.CurriculaCreate,
    name: 'Create curricula',
    description: 'Create curricula within the authorized Brand scope.',
    resource: 'curricula',
    action: 'create',
  },
  {
    code: PermissionCode.CurriculaUpdate,
    name: 'Update curricula',
    description: 'Update safe curriculum metadata within the authorized Brand scope.',
    resource: 'curricula',
    action: 'update',
  },
  {
    code: PermissionCode.CurriculaArchive,
    name: 'Archive curricula',
    description: 'Archive curricula while retaining historical structures.',
    resource: 'curricula',
    action: 'archive',
  },
  {
    code: PermissionCode.CurriculumVersionsRead,
    name: 'Read curriculum versions',
    description: 'Read curriculum versions within the authorized Brand scope.',
    resource: 'curriculum_versions',
    action: 'read',
  },
  {
    code: PermissionCode.CurriculumVersionsCreate,
    name: 'Create curriculum versions',
    description: 'Create or clone draft curriculum versions.',
    resource: 'curriculum_versions',
    action: 'create',
  },
  {
    code: PermissionCode.CurriculumVersionsUpdate,
    name: 'Update curriculum versions',
    description: 'Edit draft curriculum version structures.',
    resource: 'curriculum_versions',
    action: 'update',
  },
  {
    code: PermissionCode.CurriculumVersionsPublish,
    name: 'Publish curriculum versions',
    description: 'Publish a draft curriculum version and retire the previous version.',
    resource: 'curriculum_versions',
    action: 'publish',
  },
  {
    code: PermissionCode.CurriculumWeeksManage,
    name: 'Manage curriculum weeks',
    description: 'Manage draft curriculum week structure and ordering.',
    resource: 'curriculum_weeks',
    action: 'manage',
  },
  {
    code: PermissionCode.CurriculumModulesManage,
    name: 'Manage curriculum modules',
    description: 'Manage draft curriculum module structure and ordering.',
    resource: 'curriculum_modules',
    action: 'manage',
  },
  {
    code: PermissionCode.MaterialsRead,
    name: 'Read materials',
    description: 'Read material metadata within the authorized Brand scope.',
    resource: 'materials',
    action: 'read',
  },
  {
    code: PermissionCode.MaterialsCreate,
    name: 'Create materials',
    description: 'Create material records within a draft Curriculum version.',
    resource: 'materials',
    action: 'create',
  },
  {
    code: PermissionCode.MaterialsUpdate,
    name: 'Update materials',
    description: 'Update safe material metadata within a draft Curriculum version.',
    resource: 'materials',
    action: 'update',
  },
  {
    code: PermissionCode.MaterialsRemove,
    name: 'Remove materials',
    description: 'Remove materials within a draft Curriculum version.',
    resource: 'materials',
    action: 'remove',
  },
  {
    code: PermissionCode.MaterialsReorder,
    name: 'Reorder materials',
    description: 'Reorder materials within a draft Curriculum module.',
    resource: 'materials',
    action: 'reorder',
  },
  {
    code: PermissionCode.MaterialsUpload,
    name: 'Upload material files',
    description: 'Upload and scan a private file for a draft material.',
    resource: 'materials',
    action: 'upload',
  },
  {
    code: PermissionCode.LearningContentReadSelf,
    name: 'Read own learning content',
    description: 'Read material content only through an own bound enrollment.',
    resource: 'learning_content',
    action: 'read_self',
  },
  {
    code: PermissionCode.LearningProgressRead,
    name: 'Read learning material progress',
    description: 'Read enrollment-scoped per-material learning completion status.',
    resource: 'learning_progress',
    action: 'read',
  },
  {
    code: PermissionCode.TrainingProgressReadSelf,
    name: 'Read own training progress',
    description: 'Read server-derived progress for an exact own training enrollment.',
    resource: 'training_progress',
    action: 'read_self',
  },
  {
    code: PermissionCode.ExamsRead,
    name: 'Read exams',
    description: 'Read assessment definitions within the authorized Brand scope.',
    resource: 'exams',
    action: 'read',
  },
  {
    code: PermissionCode.ExamsCreate,
    name: 'Create exams',
    description: 'Create draft assessment definitions within the authorized Brand scope.',
    resource: 'exams',
    action: 'create',
  },
  {
    code: PermissionCode.ExamsUpdate,
    name: 'Update exams',
    description: 'Update draft assessment definitions within the authorized Brand scope.',
    resource: 'exams',
    action: 'update',
  },
  {
    code: PermissionCode.QuestionsRead,
    name: 'Read exam questions',
    description: 'Read question bank definitions within the authorized Brand scope.',
    resource: 'questions',
    action: 'read',
  },
  {
    code: PermissionCode.QuestionsCreate,
    name: 'Create exam questions',
    description: 'Create draft exam questions within the authorized Brand scope.',
    resource: 'questions',
    action: 'create',
  },
  {
    code: PermissionCode.QuestionsUpdate,
    name: 'Update exam questions',
    description: 'Update or remove draft exam questions within the authorized Brand scope.',
    resource: 'questions',
    action: 'update',
  },
  {
    code: PermissionCode.QuestionsApprove,
    name: 'Approve exam questions',
    description: 'Approve structurally valid exam questions within the authorized Brand scope.',
    resource: 'questions',
    action: 'approve',
  },
  {
    code: PermissionCode.QuestionsAiGenerate,
    name: 'Generate AI draft questions',
    description:
      'Request source-grounded AI question candidates for editable draft exams within the authorized Brand scope.',
    resource: 'questions',
    action: 'ai_generate',
  },
  {
    code: PermissionCode.ExamAttemptsStartSelf,
    name: 'Start own exam attempts',
    description: 'Start or resume an assessment attempt for an exact own enrollment.',
    resource: 'exam_attempts',
    action: 'start_self',
  },
  {
    code: PermissionCode.ExamAttemptsAnswerSelf,
    name: 'Answer own exam attempts',
    description: 'Autosave selections only for an in-progress own assessment attempt.',
    resource: 'exam_attempts',
    action: 'answer_self',
  },
  {
    code: PermissionCode.ExamAttemptsSubmitSelf,
    name: 'Submit own exam attempts',
    description: 'Submit an in-progress own assessment attempt for server-side scoring.',
    resource: 'exam_attempts',
    action: 'submit_self',
  },
  {
    code: PermissionCode.ExamAttemptsReadSelf,
    name: 'Read own exam attempts',
    description: 'Read safe history and results for own assessment attempts.',
    resource: 'exam_attempts',
    action: 'read_self',
  },
  {
    code: PermissionCode.ExamResultsRead,
    name: 'Read exam results',
    description: 'Read submitted assessment results within the authorized Brand scope.',
    resource: 'exam_results',
    action: 'read',
  },
  {
    code: PermissionCode.ReportsRead,
    name: 'Read operational reports',
    description: 'Read canonical training reporting projections within authorized Brand scope.',
    resource: 'reports',
    action: 'read',
  },
  {
    code: PermissionCode.ReportsExport,
    name: 'Export operational reports',
    description: 'Export authorized canonical training reporting projections as XLSX.',
    resource: 'reports',
    action: 'export',
  },
  {
    code: PermissionCode.CertificatesRead,
    name: 'Read certificates',
    description: 'Read and download certificates within the authorized Brand scope.',
    resource: 'certificates',
    action: 'read',
  },
  {
    code: PermissionCode.CertificatesIssue,
    name: 'Issue certificates',
    description: 'Idempotently issue eligible completed-enrollment certificates.',
    resource: 'certificates',
    action: 'issue',
  },
  {
    code: PermissionCode.CertificatesRevoke,
    name: 'Revoke certificates',
    description: 'Revoke a historical certificate without deleting it.',
    resource: 'certificates',
    action: 'revoke',
  },
  {
    code: PermissionCode.CertificatesReadSelf,
    name: 'Read own certificates',
    description: 'Read and download only the authenticated participant certificate.',
    resource: 'certificates',
    action: 'read_self',
  },
] as const;
